sudo: required
language: generic 
services:
  - docker

  before_install:
    - docker build -t amitdocker12/docker-react -f Dockerfile.dev .

    script:
    - docker run -e CI=true amit-github/docker-react npm run test
